pacientes/urls.py
from django.urls import path
from pacientes.views import Home, EscolherHorario, AgendarHorario, MinhasConsultas, consulta, CancelarConsulta

urlpatterns = [
    path('home/', Home, name='home'),
    path('escolher_horario/<int:id_dados_medicos>', EscolherHorario, name='escolher_horario'),
    path('agendar_horario/<int:id_data_aberta>/', AgendarHorario, name="agendar_horario"),
    path('minhas_consultas/', MinhasConsultas, name="minhas_consultas"),
    path('consulta/<int:id_consulta>/', consulta, name="consulta"),
    path('cancelar_consulta/<int:id_consulta>/', CancelarConsulta, name="cancelar_consulta"),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls')),
    path('medicos/', include('medicos.urls')),
    path('pacientes/', include('pacientes.urls')),
    path('', lambda request: redirect('usuarios/login'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medicos/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

def is_medico(user):
    return DadosMedico.objects.filter(user=user).exists()

class Especialidades(models.Model):
    especialidade = models.CharField(max_length=100)
    
    def __str__(self):
        return self.especialidade
    
class DadosMedico(models.Model):
    crm = models.CharField(max_length=30)
    nome = models.CharField(max_length=100)
    cep = models.CharField(max_length=15)
    rua = models.CharField(max_length=100)
    bairro = models.CharField(max_length=100)
    numero = models.IntegerField()
    rg = models.ImageField(upload_to="rg")
    cedula_identidade_medica = models.ImageField(upload_to="cim")
    foto = models.ImageField(upload_to="foto_perfil")
    descricao = models.TextField()
    valor_consulta = models.FloatField(default=100)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    especialidade = models.ForeignKey(Especialidades, on_delete=models.DO_NOTHING)
    
    def __str__(self):
        return self.user.username
    
    @property
    def proxima_data(self):
        proxima_data = DatasAbertas.objects.filter(user=self.user).filter(data__gt=datetime.now()).filter(agendado=False).order_by('data').first()
        return proxima_data
    
class DatasAbertas(models.Model):
    data = models.DateTimeField()
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    agendado = models.BooleanField(default=False)
    
    def __str__(self):
        return self.data.strftime("%d/%m/%Y às %H:%M")

pacientes/models.py
from django.db import models
from django.contrib.auth.models import User
from medicos.models import DatasAbertas
from datetime import datetime

class Consulta(models.Model):
    status_choices = (
        ('A', 'Agendada'),
        ('F', 'Finalizada'),
        ('C', 'Cancelada'),
        ('I', 'Iniciada')
    )
    paciente = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    data_aberta = models.ForeignKey(DatasAbertas, on_delete=models.DO_NOTHING)
    status = models.CharField(max_length=1, choices=status_choices, default='A')
    link = models.URLField(null=True, blank=True)
    
    @property
    def diferenca_dias(self):
        try:
            diferenca = (self.data_aberta.data.date() - datetime.now().date()).days
            return diferenca
        except AttributeError:
            return None
    
    def __str__(self):
        return f"{self.paciente.first_name} {self.paciente.last_name}"

class Documento(models.Model):
    consulta = models.ForeignKey(Consulta, on_delete=models.DO_NOTHING)
    titulo = models.CharField(max_length=30)
    documento = models.FileField(upload_to='documentos')

    def __str__(self):
        return self.titulo

pacientes/views.py
from django.shortcuts import render, redirect
from medicos.models import DadosMedico, Especialidades, DatasAbertas, is_medico
from datetime import datetime
from pacientes.models import Consulta, Documento
from django.contrib import messages
from django.contrib.messages import constants
from django.contrib.auth.decorators import login_required
from django.db.models.functions import TruncDate

@login_required
def Home(request):
    if request.method == "GET":
        medico_filtrar = request.GET.get('medico')
        especialidades_filtrar = request.GET.getlist('especialidades')
        medicos = DadosMedico.objects.exclude(user=request.user)
        minhas_consultas = Consulta.objects.filter(paciente=request.user).filter(data_aberta__data__gte=datetime.now()).filter(status="A").order_by('data_aberta__data')
        
        if medico_filtrar:
            medicos = medicos.filter(nome__icontains=medico_filtrar)
            
        if especialidades_filtrar:
            medicos = medicos.filter(especialidade_id__in=especialidades_filtrar)
              
        especialidades = Especialidades.objects.all()
        return render(request, 'home.html', {'medicos':medicos, 'especialidades':especialidades, 'is_medico': is_medico(request.user), 'minhas_consultas':minhas_consultas})

@login_required    
def EscolherHorario(request, id_dados_medicos):
    if request.method == "GET":
        medico = DadosMedico.objects.get(id=id_dados_medicos)
        datas_abertas = DatasAbertas.objects.filter(user=medico.user).filter(data__gte=datetime.now()).filter(agendado=False).order_by('data')
        return render(request, 'escolher_horario.html', {'medico': medico, 'datas_abertas': datas_abertas, 'is_medico': is_medico(request.user)})

@login_required    
def AgendarHorario(request, id_data_aberta):
    if request.method == "GET":
        data_aberta = DatasAbertas.objects.get(id=id_data_aberta)
        horario_agendado = Consulta(
            paciente=request.user,
            data_aberta=data_aberta
        )
        horario_agendado.save()
        data_aberta.agendado = True
        data_aberta.save()
        messages.add_message(request, constants.SUCCESS, 'Consulta agendada com sucesso.')
        return redirect('/pacientes/minhas_consultas/')

@login_required    
def MinhasConsultas(request):
    if request.method == "GET":
        data = request.GET.get("data")
        especialidade = request.GET.get("especialidade")
        minhas_consultas = Consulta.objects.filter(paciente=request.user).order_by('-data_aberta__data')
        
        if data:
            data = datetime.strptime(data, '%Y-%m-%d').date()
            minhas_consultas = minhas_consultas.annotate(data_aberta_date=TruncDate('data_aberta__data')).filter(data_aberta_date=data)
        if especialidade:
            minhas_consultas = minhas_consultas.filter(data_aberta__user__dadosmedico__especialidade__id=especialidade)

        especialidades = Especialidades.objects.all()
        return render(request, 'minhas_consultas.html', {'minhas_consultas': minhas_consultas, 'is_medico': is_medico(request.user), 'especialidades':especialidades})

@login_required
def consulta(request, id_consulta):
    if request.method == "GET":
        consulta = Consulta.objects.get(id=id_consulta)
        dados_medico = DadosMedico.objects.get(user=consulta.data_aberta.user)
        documentos = Documento.objects.filter(consulta=consulta)
        return render(request, 'consulta.html', {'consulta': consulta, 'dados_medico': dados_medico, 'is_medico': is_medico(request.user), 'documentos':documentos})
    
@login_required
def CancelarConsulta(request, id_consulta):
    if request.method == "GET":
        consulta = Consulta.objects.get(id=id_consulta)
        if request.user != consulta.paciente:
            messages.add_message(request, constants.ERROR, 'Essa consulta não é sua.')
            return redirect('/pacientes/home/')
        
        consulta.status = 'C'
        consulta.save()
        return redirect(f'/pacientes/consulta/{id_consulta}')

pacientes/templates/consulta.html
{% extends "shared/base.html" %}
{% load static %}
  {% block 'title' %}
  Consulta - Healing
  {% endblock %}
{% block 'head' %}
    <link rel="stylesheet" href="{% static 'medicos/css/abrir_horario.css' %}">
    <link rel="stylesheet" href="{% static 'usuarios/css/usuarios.css' %}">
    <link rel="stylesheet" href="{% static 'medicos/css/cadastro_medico.css' %}">
    <link rel="stylesheet" href="{% static 'pacientes/css/home.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
{% endblock 'head' %}
{% block 'body' %}
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    {% include "partials/_navbar.html" %}
    <br><br>
    <div class="container">
        {% if consulta.status == 'C' %}
            <div class="alert alert-danger" role="alert">
                Consulta cancelada
            </div>
        {% elif consulta.status == 'F' %}
            <div class="alert alert-success" role="alert">
                Consulta Finalizada
            </div>
        {% elif consulta.status == 'I' %}
            <div class="alert alert-primary" role="alert">
                Consulta inicializada, acesse o link imediatamente!
            </div>
        {% endif %}
        <div class="row">
            <div class="col-md-8">
                <div class="row">
                    <div class="col-md-3"><img src="{{dados_medico.foto.url}}" class="foto-perfil-card-lg" alt=""></div>
                    <div class="col-md">
                        <p style="font-size: 20px" class="p-bold">Dr(a). {{dados_medico.nome}} <i class="bi bi-patch-check-fill icon-main"></i></p>
                        <p>{{dados_medico.descricao}}</p>
                        <p class="p-bold">{{consulta.data_aberta.data}}</p>
                        {% if consulta.status != 'C' and consulta.status != 'F' %}<a href="#" onclick="event.preventDefault(); confirmarCancelamento('{% url 'cancelar_consulta' consulta.id %}')" class="btn btn-danger">Cancelar consulta</a>{% endif %}
                    </div>
                </div> 
                <hr>
                <br>
                <div class="row">
                    <div class="col-md">
                        
                        <p><i class="color-dark bi bi-check-circle-fill"></i> Consulta agendada</p>
                    </div>
                    <div class="col-md">
                        <p><i class="{% if consulta.status == 'F' %}color-dark{% endif %} bi bi-check-circle-fill"></i> Consulta realizada</p>
                    </div>
                    <div class="col-md">
                        <p><i class="bi bi-check-circle-fill"></i> Consulta Avaliada</p>
                    </div>
                </div>
                <hr>
                <h3 class="p-bold">Detalhes da consulta</h3>
                <p style="font-size:20px"><i class="bi bi-calendar3 color-dark"></i>&nbsp {{consulta.data_aberta.data}}</p>
                <p style="font-size:20px"><i class="bi bi-tag-fill color-dark"></i></i>&nbsp R$ {{dados_medico.valor_consulta|floatformat:2}}</p>
                {% if consulta.status == 'F' or consulta.status == 'C' %}
                {% else %}
                    <a href="https://calendar.google.com/calendar/render?action=TEMPLATE&text=Consulta com Dr(a) {{dados_medico.nome}}&dates={{consulta.data_aberta.data|date:'Ymd'}}T{{consulta.data_aberta.data|date:'His' }}/{{consulta.data_aberta.data|date:'Ymd'}}T{{consulta.data_aberta.data|date:'His'}}&details={{dados_medico.especialidade}}&location={{dados_medico.rua}}, {{dados_medico.numero}}" target="_blank" class="btn btn-dark-color-outline btn-lg{% if consulta.status == 'F' or consulta.status == 'C' %} disabled{% endif %}">Adicione em seu calendário!</a>
                {% endif %}    
                <hr>
                {% if consulta.status == 'F' or consulta.status == 'C' %}
                {% else %}
                    <h3 class="p-bold">Como acessar ?</h3>
                    <p>No horário da consulta acesse o link disponível abaixo</p>
                    {% if consulta.status == 'I' and consulta.link and consulta.status != 'F' and consulta.status != 'C' %}
                        <a href="{{consulta.link}}" class="btn btn-success btn-dark-color btn-lg" target="_blank">Acessar consulta</a>
                    {% else %}
                        <a href="#" class="btn btn-success btn-dark-color btn-lg disabled" >Acessar consulta</a>
                    {% endif %}
                    <hr>
                {% endif %}
                {% if consulta.status != 'F' %}
                {% else %}
                    <h3 class="p-bold">Meus documentos</h3>
                    <br>
                    {% for documento in documentos %}
                        <br>
                            <a href="{{documento.documento.url}}" class="link documentos" target="_blank"><i class="bi bi-file-arrow-down"></i> {{documento.titulo}} - {{documento.consulta.data_aberta.data.year}}</a>
                        <br><br>
                    {% endfor %}
                    <br><br><br><br>
                {% endif %}
            </div>
            <div class="col-md"></div>
        </div>
    </div>
    <script>
        function confirmarCancelamento(url) {
            Swal.fire({
                title: 'Você tem certeza?',
                text: "Cancelar esta consulta?",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Sim, cancelar!',
                cancelButtonText: 'Não, manter!'
            }).then((result) => {
                if (result.isConfirmed) {
                    window.location.href = url;
                }
            })
        }
    </script>
{% endblock 'body' %}

pacientes/templates/escolher_horario.html
{% extends "shared/base.html" %}
{% load static %}
  {% block 'title' %}
  Escolher horário - Healing
  {% endblock %}
{% block 'head' %}
    <link rel="stylesheet" href="{% static 'medicos/css/abrir_horario.css' %}">
    <link rel="stylesheet" href="{% static 'usuarios/css/usuarios.css' %}">
    <link rel="stylesheet" href="{% static 'medicos/css/cadastro_medico.css' %}">
    <link rel="stylesheet" href="{% static 'pacientes/css/home.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
{% endblock 'head' %}
{% block 'body' %}
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    {% include "partials/_navbar.html" %}
    <div class="container">
        <br><br>
        <div class="row">
            <div class="col-md-8">
                <div class="row">
                    <div class="col-md-3"><img src="{{medico.foto.url}}" class="foto-perfil-card-lg" alt=""></div>
                    <div class="col-md">
                        <p style="font-size: 20px" class="p-bold">Dr(a). {{medico.nome}} <i class="bi bi-patch-check-fill icon-main"></i></p>
                        <p>{{medico.descricao}}</p>
                    </div>
                </div> 
                <br>
                {% if messages %}
                    <br>
                    {% for message in messages %}
                        <section class="alert {{message.tags}}">
                            {{message}}
                        </section>
                    {% endfor %}
                {% endif %} 
                <hr>
                <div class="row">
                    {% for data_aberta in datas_abertas %}
                        <div class="col-md-3">
                            <a class="link" href="#" onclick="event.preventDefault(); confirmarConsulta('{% url 'agendar_horario' data_aberta.id %}', '{{data_aberta.data}}')">
                            <div class='selecionar-dia'>
                            <div class="header-dias">
                                <span class="mes">
                                {{data_aberta.data|date:"F"}}
                                </span>
                                <span class="dia-semana">
                                {{data_aberta.data|date:"l"}}
                                </span>
                            </div>
            
                            <div class="conteudo-data" style="text-align:center;">
                                {{data_aberta.data|date:"d/m/y \à\s H:i" }}
                            </div>
                            </div>
                        </a>
                        <br>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-4">
            </div>
        </div>
    </div>
    <script>
        function confirmarConsulta(url, data) {
            Swal.fire({
                title: 'Você tem certeza?',
                text: "Marcar consulta para " + data + "?",
                icon: 'question',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Sim, marcar!',
                cancelButtonText: 'Não, cancelar!'
            }).then((result) => {
                if (result.isConfirmed) {
                    window.location.href = url;
                }
            })
        }
    </script>
{% endblock 'body' %}

pacientes/templates/home.html
{% extends "shared/base.html" %}
{% load static %}
  {% block 'title' %}
  Home - Healing
  {% endblock %}
{% block 'head' %}
    <link rel="stylesheet" href="{% static 'medicos/css/abrir_horario.css' %}">
    <link rel="stylesheet" href="{% static 'usuarios/css/usuarios.css' %}">
    <link rel="stylesheet" href="{% static 'medicos/css/cadastro_medico.css' %}">
    <link rel="stylesheet" href="{% static 'pacientes/css/home.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
{% endblock 'head' %}
{% block 'body' %}
    {% include "partials/_navbar.html" %}
    <br><br>
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <p style="font-size: 25px" class="p-bold">Olá, <span class="color-dark">{{request.user.first_name}} {{request.user.last_name}}.</span></p>
                <form action="{% url 'home' %}" post="GET">
                    <input type="text" class="form-control shadow-main-color" placeholder="Busque por profissionais ..." name="medico">
                    <br>
                    <div class="especialidades">
                        {% for especialidade in especialidades %}
                            <input type="checkbox" name="especialidades" value="{{especialidade.id}}">
                            <span class="badge bg-secondary">
                                {{especialidade}}
                            </span>
                        {% endfor %}
                    </div>
                    <br>
                    <input type="submit" value="Filtrar" class="btn btn-success btn-dark-color">
                </form>
                <hr>
                <div class="list-medicos">
                {% for medico in medicos %}
                    <div class="card-medicos shadow-main-color">
                        <div class="row">
                            <div class="col-md-3"><img src="{{medico.foto.url}}" class="foto-perfil-card" alt=""></div>
                            <div class="col-md">
                                <p style="font-size: 20px" class="p-bold">Dr(a). {{medico.nome}} <i class="bi bi-patch-check-fill icon-main"></i></p>
                                <p>{{medico.descricao}}</p>
                            </div>
                        </div>  
                        <p><i class="bi bi-map icon-main"></i>&nbsp&nbsp{{medico.rua}}</p>
                        <p><i class="bi bi-calendar2-week icon-main"></i>&nbsp&nbspProxima data: 
                            {% if medico.proxima_data %}
                                {{medico.proxima_data.data|date:"d/m/Y \à\s H:i"}}
                                <a href="{% url 'escolher_horario' medico.id %}" class="btn btn-success btn-dark-color">Agendar</a>
                            {% else %}
                                Aguarde uma data.
                            {% endif %}
                    </div>
                    <br>
                {% endfor %}
                </div>
            </div>
            <div class="col-md-4">
                <p style="font-size: 25px" class="p-bold">Lembretes</p>
                <p class="bg-main-lembrete">
                    {% if minhas_consultas %}
                        {% for consulta in minhas_consultas %}
                            <span class="p-bold"><i class="bi bi-exclamation-triangle-fill icon-differential"></i>&nbsp&nbsp Consulta com {{consulta.data_aberta.user.dadosmedico_set.first.nome}} {% if consulta.diferenca_dias == 0 %} hoje {% else %}em {{consulta.diferenca_dias}}{% if consulta.diferenca_dias == 1 %} dia. {% else %} dias.{% endif %}{% endif %}
                            </span><br>
                        {% endfor %}
                    {% else %}
                        <span class="p-bold">
                            <i class="bi bi-calendar-check icon-differential"></i>&nbsp;&nbsp; Sem consultas agendadas.
                        </span>
                    {% endif %}
                </p> 
            </div>
        </div>
    </div>
{% endblock 'body' %}

pacientes/templates/minhas_consultas.html
{% extends "shared/base.html" %}
{% load static %}
  {% block 'title' %}
  Minhas consultas - Healing
  {% endblock %}
{% block 'head' %}
    <link rel="stylesheet" href="{% static 'medicos/css/abrir_horario.css' %}">
    <link rel="stylesheet" href="{% static 'usuarios/css/usuarios.css' %}">
    <link rel="stylesheet" href="{% static 'medicos/css/cadastro_medico.css' %}">
    <link rel="stylesheet" href="{% static 'pacientes/css/home.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
{% endblock 'head' %}
{% block 'body' %}
    {% include "partials/_navbar.html" %}
    <div class="container">
        {% if messages %}
            <br>
                {% for message in messages %}
                    <section class="alert {{message.tags}}">
                        {{message}}
                    </section>
                {% endfor %}
            {% endif %} 
        <br>
        <h2><span class="color-dark">Minhas consultas</span></h2>
        <div class="row">
            <div class="col-md">
                <form action="">
                <select name="especialidade" class="form-select shadow-main-color">
                        <option value="">Escolha uma especialidade</option>
                    {% for especialidade in especialidades %}
                        <option value="{{especialidade.id}}">{{especialidade}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-md">
                <input type="date" name="data" id="" class="form-control shadow-main-color" placeholder="Data da consulta">
            </div>
            <div class="col-md">
                <input type="submit" value="Filtrar" class="btn btn-dark-color-outline">
            </form>
            </div>
        </div>
        <br>
        <div class="list-minhas-consultas">
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Médico</th>
                    <th scope="col">Status</th>
                    <th scope="col">Data</th>
                  </tr>
                </thead>
                <tbody>
                    {% for consulta in minhas_consultas  %}
                        <tr>
                            <td><a href="{% url 'consulta' consulta.id %}" class="{% if consulta.status == 'A' or consulta.status == 'I' %}link-primary{% elif consulta.status == 'F' %}link-success{% else %}link-danger{% endif %} link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Dr(a). {{consulta.data_aberta.user.dadosmedico_set.first.nome}}</a></td>
                            <td>{{consulta.get_status_display}}</td>
                            <td>{{consulta.data_aberta.data}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
              </table>
        </div>
    </div>
{% endblock 'body' %}